### ISSUE TITLE
New talk with examples and comparison of Reason to Flow and TypeScript

### ISSUE THREAD

**Issue by udeshx** [vramana/awesome-reasonml#20]
Hi,

What would you recommend I do to have this talk added to the list?

It's a good talk with examples which provides a comparison of Reason to Flow and TypeScript

2017 06 – [@bassjacob](https://github.com/bassjacob/) – [Node.ninjas Sydney](https://www.meetup.com/en-AU/sydney-node-ninjas/) – [Everything happens for a Reason ](https://www.youtube.com/watch?v=lLqLqFgsimQ&ab_channel=ANZCoders)

Thanks
UdeshX

**Comment by vramana** [comment]
Ofcourse.

**Comment by vramana** [comment]
Added it.

**Comment by udeshx** [comment]
Thanks
